# Site settings
title: teachmescale.com
email: mkorenkov@gmail.com
author: Max Korenkov
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teachmescale.com" # the base hostname & protocol for your site
twitter_username: ibo_ezhe
github_username:  mkorenkov
timezone: America/Los_Angeles 

# Build settings
markdown: kramdown
